### PR TITLE
Fix #58 - Fix inbox_members_controller rubocop errors

### LINKED ISSUE #58: Fix "Rubocop/Metrics/MethodLength" issue in app/controllers/api/v1/inbox_members_controller.rb
Method has too many lines. [15/10]

https://codeclimate.com/github/chatwoot/chatwoot/app/controllers/api/v1/inbox_members_controller.rb#issue_5d87480b87cf1900010002c5

### PR DESCRIPTION
**Pull request by ancarosu**

### CODE REVIEW

File: app/controllers/api/v1/inbox_members_controller.rb [hunk 1]
```diff
@@ -1,49 +1,52 @@
...
-  def create #update also done via same action
-    #get all the user_ids which the inbox currently has as members.
-    #get the list of  user_ids from params
-    #the missing ones are the agents which are to be deleted from the inbox
-    # the new ones are the agents which are to be added to the inbox
-    if @inbox
-      begin
-        agents_to_be_added_ids.each do |user_id|
-          @inbox.add_member(user_id)
+module Api
```
Comment (subintp) [inline app/controllers/api/v1/inbox_members_controller.rb]: @ancarosu  Can you add test cases for this. We are getting a lot of PRs these days. Its high time to add tests so that we can move fast.

Comment (ancarosu) [reply app/controllers/api/v1/inbox_members_controller.rb]: Okay, will do!

**Comment by pranavrajs** [comment]
@ancarosu Thanks for the PR, could you please rebase with the master branch to fix the conflicts? Otherwise, PR looks good.

As you said, I've added a new issue to add tests for this controller. https://github.com/chatwoot/chatwoot/issues/118
Please feel free to assign this to yourself.
