### PR TITLE
bug: fixes error in creating a new one off campaign

### LINKED ISSUE #3000: bug: Error in creating a new one off campaign
### Discussed in https://github.com/chatwoot/chatwoot/discussions/2991

<div type='discussions-op-text'>

<sup>Originally posted by **mkbadri** September 10, 2021</sup>
Hi team, great work on the solution. Keen to explore more and just kicked off looking at chatwoot and looks very promising

I was trying to setup some campaigns to evaluate the process but I was stuck in creating it. I am not sure if it's a bug or work in progress. Or even a configuration issue.

image

image

The response says "Inbox Unsupported Inbox type" while creating the campaign - what type of Inboxes are supported for campaigns - email? SMS? WhatsApp? Website?

I tried getting some info from this [documentation](https://www.chatwoot.com/docs/product/features/campaigns) but no luck on the one-off. Even in the ongoing campaign - what are the supported values?

Appreciate your assistance.

</div>

**Solution**

- Stripe Twilo WhatsApp inboxes in One-off campaign create campaign model

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3000 

## Type of change

**Screenshot**

**After**
Screenshot 2021-09-22 at 2 26 42 PM

**Before**
Screenshot 2021-09-22 at 2 26 25 PM

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Can be tested by going to the campaign and select the one-off option in the side panel and then by creating a new one  

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/javascript/dashboard/store/modules/inboxes.js [hunk 1]
```diff
@@ -73,6 +73,9 @@ export const getters = {
       item => item.channel_type === INBOX_TYPES.TWILIO
     );
   },
+  getTwilioSMSInboxes($state) {
+    return $state.records.filter(item => item.medium === 'sms');
```
Comment (pranavrajs) [inline app/javascript/dashboard/store/modules/inboxes.js:77]: Please add a check for channel type as well.

**Review by nithindavid — APPROVED** [review]
