### PR TITLE
Fix: added validation for custom and additional attribute

### LINKED ISSUE #297: On Heroku Cannot delete agent (John) created by seed file
**Describe the bug**
After deploying to heroku, I configured the SMTP server (Sendgrid)
- Added a new Agent (Administrator)
- Confirmed Agent
- Tried to delete John
Received message "Cannot connect to woot server..."

Was able to change John to agent, but also not able to change password or email.

**Desktop (please complete the following information):**
- macOS 10.15.1
- Firefox
- 70.0.1 64 bit

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Added params length validation for additional and custom attributes.

Fixes: https://github.com/chatwoot/product/issues/297

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added Test cases for the same. Tested on local if the normal additional/custom attributes adding is working fine.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: spec/models/conversation_spec.rb [hunk 1]
```diff
@@ -58,6 +58,35 @@
...
+        inbox: inbox,
+        assignee: nil
+      )
+    end
+
+    it 'validate length of additional_attributes value' do
+      conversation.additional_attributes = { company_name: 'some_company' * 200 }
+      conversation.valid?
+      error_messages = conversation.errors.messages
+      expect(error_messages[:additional_attributes][0]).to eq('company_name length should be < 1500')
```
Comment (sojan-official) [inline spec/models/conversation_spec.rb:79]: let's also add a numeric value to these specs

File: spec/models/conversation_spec.rb [hunk 2]
```diff
@@ -58,6 +58,35 @@
...
+    end
+
+    it 'validate length of custom_attributes value' do
+      conversation.custom_attributes = { company_name: 'some_company' * 200 }
+      conversation.valid?
+      error_messages = conversation.errors.messages
+      expect(error_messages[:custom_attributes][0]).to eq('company_name length should be < 1500')
```
Comment (sojan-official) [inline spec/models/conversation_spec.rb:86]: let's also add a numeric value to these specs

**Review by sojan-official — COMMENTED** [review]
minor comment. other wise looks good

File: app/models/jsonb_attributes_length_validator.rb [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+      validate_keys(key, attribute_value)
+    end
+  end
+
+  def validate_keys(key, attribute_value)
+    case attribute_value.class.name
+    when 'String'
+      @record.errors.add @attribute, "#{key} length should be < 1500" if attribute_value.length > 1500
+    when 'Integer'
+      @record.errors.add @attribute, "#{key} value maximun limit should be < 9999999999" if attribute_value > 9_999_999_999
```
Comment (sojan-official) [inline app/models/jsonb_attributes_length_validator.rb:18]: `maximun` typo

Comment (sojan-official) [reply app/models/jsonb_attributes_length_validator.rb:18]: we can do ` value should be <  `
