### PR TITLE
fix: Handle more rest client exceptions

### LINKED ISSUE #2085: RestClient::ServiceUnavailable response in webhooks should not throw error
https://sentry.io/share/issue/f85b6ee07f0846ef9cc1a37deada5488/

- Catch `RestClient::ServiceUnavailable` while executing the webhooks.

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #2085

### CODE REVIEW

File: lib/exception_list.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@ module ExceptionList
   REST_CLIENT_EXCEPTIONS = [RestClient::NotFound, RestClient::GatewayTimeout, RestClient::BadRequest,
                             RestClient::MethodNotAllowed, RestClient::Forbidden, RestClient::InternalServerError,
                             RestClient::Exceptions::OpenTimeout, RestClient::Exceptions::ReadTimeout,
-                            RestClient::MovedPermanently, SocketError].freeze
+                            RestClient::MovedPermanently, RestClient::ServiceUnavailable, SocketError].freeze
```
Comment (sojan-official) [inline lib/exception_list.rb:5]: let also add Errno::ECONNREFUSED to the list

**Review by sojan-official — APPROVED** [review]
