### PR TITLE
Bug: Migrate messages while merging contact

### LINKED ISSUE #623: Bug: PG Violation Error while updating email from widget
- [ ] PG Violation error while updating email from widget

### PR DESCRIPTION
**Pull request by pranavrajs**
Fixes #623

### CODE REVIEW

File: spec/actions/contact_merge_action_spec.rb [hunk 1]
```diff
@@ -32,6 +33,13 @@
       end
     end
 
+    context 'when mergee contact has messages' do
+      it 'moves the contact inboxes to base contact' do
```
Comment (sojan-official) [inline spec/actions/contact_merge_action_spec.rb]: contact messages to base contact
