### PR TITLE
fix: Record audio in wav format for web/facebook

### LINKED ISSUE #7045: [CW-1688] [CW-1490] Instagram voice record option is not working
Instagram only supports acc, m4a, wav, mp4 formats. We are recording the audio in either webm or ogg. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1490](https://linear.app/chatwoot/issue/CW-1490/instagram-voice-record-option-is-not-working)</sub>

<sub>[CW-1688](https://linear.app/chatwoot/issue/CW-1688/[cw-1490]-instagram-voice-record-option-is-not-working)</sub>

### PR DESCRIPTION
**Pull request by giquieu**
# Pull Request Template

## Description

Fixes #7045 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested sending messages on Facebook and Web boxes and sending audio in .wav format.
WhatsApp box sends audio in .ogg.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue [hunk 1]
```diff
@@ -134,6 +132,11 @@ export default {
   },
   methods: {
     deviceReady() {
+      if (this.player.record().engine instanceof OpusRecorderEngine) {
+        if (this.audioRecordFormat === AUDIO_FORMATS.WEBM) {
```
Comment (muhsin-k) [inline app/javascript/dashboard/components/widgets/WootWriter/AudioRecorder.vue:136]:
```suggestion
        if (this.audioRecordFormat === AUDIO_FORMATS.WAV) {
```
Let's add a new value for the `wav` format - https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/shared/constants/messages.js#L84

```
export const AUDIO_FORMATS = {
  WEBM: 'audio/webm',
  OGG: 'audio/ogg',
  WAV: 'audio/wav',
};
```

**Review by muhsin-k — COMMENTED** [review]
@giquieu Nice work ❤️.

Please take a look at the comments.

**Review by muhsin-k — APPROVED** [review]
