### PR TITLE
fix:  Send push notification on `bot_handoff`

### LINKED ISSUE #7587: Push notification isn't generated for bot hand off
### Describe the bug

Push notifications aren't generated for hand offs like they are for new conversations.
This creates problems for the agents as they are unable to attend on time.

### To Reproduce

1. Setup push notifications and a bot
2. Start a dummy conversation from the web widget
3. After the bot hand off, no push notification is generated

### Expected behavior

A 'Conversation Created' push notification should be generateed.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

_No response_

### Browser and version

_No response_

### Docker (if applicable)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Jatin-MYST**
## Description

Send a 'Conversation Created' push notification when the bot does a hand_off.

The function is a copy of conversation_created in the same class.
Only the name is changed.
The new function is automatically fired on bot hand_off.

fixes #7587 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

I have a test instance of CW on Ubuntu 20.04 VM on AWS.
I had the notifications and the bot all setup.
I tested the notifications weren't coming through.
I made the changes and restarted CW.
When I tested it again, It was sending the push notifications.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sojan-official** [comment]
Thank you so much for your contribution. We truly appreciate your efforts. 🙏 

Our team will prioritize reviewing and testing your changes according to our existing schedule and workload. 
Should there be a need for any further actions or information from your side, we'll follow up here. 📨

Once again, we're grateful for your involvement and contribution to our community. 🚀🌟 🙌 

----
note to team:  we need to add backend  specs to cover this case before merging

**Comment by sojan-official** [comment]
@muhsin-k  could you take a look at this PR and see if we can include this in the new notification changes ?

File: app/listeners/notification_listener.rb [hunk 1]
```diff
@@ -1,4 +1,18 @@
 class NotificationListener < BaseListener
+  def conversation_bot_handoff(event)
```
Comment (muhsin-k) [inline app/listeners/notification_listener.rb:2]: @Jatin-MYST Sorry for the late response. It seems like a good enhancement. Could you please add the specs for it? We will test and merge it after that.

Comment (Jatin-MYST) [reply app/listeners/notification_listener.rb:2]: @muhsin-k 
Hey, apologies but I am unable to add the specs.
I am not that familiar with RoR and the testing package in use.
I have been using this change on my self-hosted instance ever since i submitted this PR and it has been working fine.
Can someone please add the tests instead?

**Review by muhsin-k — APPROVED** [review]
