### PR TITLE
Fix: Pagination bug with filters payload

### LINKED ISSUE #3739: API call is failing on selecting load more conversations after applying filter
**Describe the bug**

The API call is failing when we click to load more conversations after applying the filter.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to Dashboard and open the filter modal
2. Click on status -> open and apply filter and now you can see the filtered conversation.
3. Open dev tool and go to Network tab and verify the filters API and go back to dashboard
4. Scroll down to and select Load more conversations after that you can see the API call is getting an error.
5. You can see the steps in the below screen recording.

https://user-images.githubusercontent.com/64252451/149061127-5f48c359-9816-49db-b854-4a46e4dc6325.mov

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 98

### PR DESCRIPTION
**Pull request by fayazara**
# Pull Request Template

## Description

Fixes the pagination error which was causing filter api to return a 500 error.

Fixes #3739 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/components/ChatList.vue [hunk 1]
```diff
@@ -346,6 +346,9 @@ export default {
       if (!this.hasAppliedFilters) {
         this.fetchConversations();
       } else {
+        this.appliedFilters[
+          this.appliedFilters.length - 1
+        ].query_operator = null;
```
Comment (nithindavid) [inline app/javascript/dashboard/components/ChatList.vue:351]: Is there a way to remove the query operator when it's applied?

Comment (fayazara) [reply app/javascript/dashboard/components/ChatList.vue:351]: You mean when making the api request?

Comment (nithindavid) [reply app/javascript/dashboard/components/ChatList.vue:351]: No, Like the applied filter object shouldn't coming with the non empty `query_operator` in the first place I guess. That would be the root cause of this problem. 

@iamsivin  also came across this issue in another place, So fixing the root would be the best case scenario.

Comment (nithindavid) [reply app/javascript/dashboard/components/ChatList.vue:351]: Possibly in `app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue`

Comment (fayazara) [reply app/javascript/dashboard/components/ChatList.vue]: @nithindavid We need to remove this manually because there is no way of knowing if a filter appended in the list would be the last unless we click submit.

But I have moved removing this operator to the payload generator helper method in https://github.com/chatwoot/chatwoot/pull/3747/commits/18e10fc6a8e824ab6e4e3256c037bee9a7642509, so this has to be never done manually in our logic. Is be this okay?

File: app/javascript/dashboard/helper/filterQueryGenerator.js [hunk 2]
```diff
@@ -11,7 +11,7 @@ const generatePayload = data => {
     }
     return item;
   });
-
+  payload[payload.length - 1].query_operator = null;
```
Comment (nithindavid) [inline app/javascript/dashboard/helper/filterQueryGenerator.js:14]:
```suggestion
// For every query added, the query_operator is set default to and so the
// last query will have an extra query_operator, this would break the api. 
// Setting this to null for all query payload

  payload[payload.length - 1].query_operator = null;
```

**Review by nithindavid — APPROVED** [review]
