### PR TITLE
fix: Remove IMAP and SMTP email validation

### LINKED ISSUE #3544: IMAP SMTP Username must be mail adress
In v2.0.0 the smtp and imap username for a email channel must be a mail adress - in my case its a simple username without the domain part. 
Maybe you can cancle the validation in further releases.

for everyone other facing this problem - with the chrome dev tools you can delete the the disable class from the submit button so you can save it - at least for the IMAP setting.
this workarround isnt working for the SMTP setting.

Edit:

also working for SMTP - used the wrong port (in my case 587)- shame on me ;)

kind regards, 
thomas

### PR DESCRIPTION
**Pull request by aswindevps**
## Description

This change allows the user to use email, username, and API key for configuring IMAP and SMTP.
Also, users can send emails using the inbox mail address with SMTP.

Fixes #3544

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

1. Verified conversation continuity using IMAP & SMTP.
2. Added spec to validate the change.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/jobs/inboxes/fetch_imap_emails_job.rb [hunk 1]
```diff
@@ -26,7 +26,7 @@ def process_mail_for_channel(channel)
     Mail.defaults do
```
Comment (sojan-official) [inline app/jobs/inboxes/fetch_imap_emails_job.rb:26]: can we also take a quick look at the #TODO comment here ? possibly something like

```
mailer_retriever = Mail.retriever_method.new :imap, address: channel.imap_address,
                              port: channel.imap_port,
                              user_name: channel.imap_email,
                              user_name: channel.imap_login,
                              password: channel.imap_password,
                              enable_ssl: channel.imap_enable_ssl
mail_retriever.find ....
```

**Review by sojan-official — COMMENTED** [review]
LGTM
added a Minor comment which we can take forward in another ticket if it requires significant effort.

File: app/jobs/inboxes/fetch_imap_emails_job.rb (hunk 1 above)
Comment (aswindevps) [reply app/jobs/inboxes/fetch_imap_emails_job.rb:26]: @sojan-official can we take this as a separate issue?
