### PR TITLE
bug: Adds meaningful alert error message if file upload fails

### LINKED ISSUE #2928: bug: Show meaningful error message if file upload fails
Message attachment support the following types -> 'image/png', 'image/jpeg', 'image/gif', 'image/bmp', 'image/tiff', 'application/pdf', 'audio/mpeg', 'video/mp4', 'audio/ogg', 'text/csv. Show proper error message If user try to upload a unsupported formats

**Steps to reproduce**
- Go to a conversation 
- Upload `svg` file via drag and drop

**Screenshots**
Screenshot 2021-08-31 at 4 08 15 PM

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description

Fixes #2928 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

It can be tested by attaching an unsupported file like SVG by drag and drop and sent it.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue [hunk 1]
```diff
@@ -347,7 +347,7 @@ export default {
           await this.$store.dispatch('sendMessage', messagePayload);
           this.$emit('scrollToMessage');
         } catch (error) {
-          // Error
+          this.showAlert(this.$t('CONVERSATION.FILE_FORMAT_ERROR'));
```
Comment (muhsin-k) [inline app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue:350]:
```suggestion
          const errorMessage = error?.response?.message || this.$t('CONVERSATION.MESSAGE_ERROR');
          this.showAlert(errorMessage);
```

Add a generic value for `MESSAGE_ERROR`

**Review by muhsin-k — APPROVED** [review]
