### PR TITLE
fix: Prevent race condition in conversation dataFetched flag

### LINKED ISSUE #13444: Race condition in setActiveChat loses dataFetched, permanently blocking message pagination (root cause of #10373)
### Describe the bug

Message pagination (scroll-up to load older messages) intermittently breaks due to a race condition in the `setActiveChat` Vuex action. When broken, the loading spinner appears but **no HTTP request is fired** — the frontend never calls the messages API. Refreshing the page sometimes fixes and sometimes re-breaks the issue.

This is the same bug reported in #10373 (closed as not planned due to lack of root cause). We've now identified the exact root cause and have a proposed fix.

### Root Cause

In `actions.js`, `setActiveChat` sets `dataFetched` directly on a local JavaScript object reference **after an `await`**:
```js
async setActiveChat({ commit, dispatch }, { data, after }) {
  commit(types.SET_CURRENT_CHAT_WINDOW, data);
  commit(types.CLEAR_ALL_MESSAGES_LOADED);
  if (data.dataFetched === undefined) {
    try {
      await dispatch('fetchPreviousMessages', { ... });
      data.dataFetched = true;   // ← BUG: sets on local reference, not via mutation
    } catch (error) {}
  }
},
```

During the `await`, if any WebSocket event arrives (conversation update, status change, typing indicator, agent assignment, etc.), the `UPDATE_CONVERSATION` mutation in `index.js` replaces the conversation object in the store:
```js
[types.UPDATE_CONVERSATION](_state, conversation) {
  const { messages, ...updates } = conversation;
  allConversations[index] = { ...selectedConversation, ...updates };  // new object
}
```

After the `await` resolves, `data.dataFetched = true` sets the property on the **old, orphaned object** — the new one in the store still has `dataFetched: undefined`.

Then in `MessagesView.vue`, `fetchPreviousMessages` checks:
```js
const shouldLoadMoreMessages =
  this.currentChat.dataFetched === true &&  // undefined === true → false
  !this.listLoadingStatus &&
  !this.isLoadingPrevious;
```

Since `dataFetched` is `undefined`, pagination is permanently blocked for that conversation.

### Proof

While the bug was active on a conversation, we ran the following in the browser console:
```js
const store = document.querySelector('#app').__vue_app__.config.globalProperties.$store;
const conv = store.state.conversations.allConversations.find(c => c.id === 184);
console.log(conv.dataFetched);  // undefined
conv.dataFetched = true;        // force-set it
// Scrolling up immediately works after this — messages load normally
```

We also confirmed:
- `store.getters.getAllMessagesLoaded` → `false` (store knows there are more messages)
- `store.dispatch('fetchPreviousMessages', { conversationId: 184, before: 1066309 })` → works perfectly, messages appear
- Direct `curl` to the messages API → returns all messages (HTTP 200)
- The **only** thing blocking pagination is `dataFetched === undefined`

### Proposed Fix

**1. Add a new mutation type** in `mutation-types.js`:
```js
SET_CHAT_DATA_FETCHED: 'SET_CHAT_DATA_FETCHED',
```

**2. Add the mutation handler** in `store/modules/conversations/index.js`:
```js
[types.SET_CHAT_DATA_FETCHED](_state) {
  const [chat] = getSelectedChatConversation(_state);
  if (chat) {
    chat.dataFetched = true;
  }
},
```

**3. Use the mutation in `setActiveChat`** in `actions.js`:
```js
async setActiveChat({ commit, dispatch }, { data, after }) {
  commit(types.SET_CURRENT_CHAT_WINDOW, data);
  commit(types.CLEAR_ALL_MESSAGES_LOADED);
  if (data.dataFetched === undefined) {
    try {
      await dispatch('fetchPreviousMessages', {
        after,
        before: data.messages[0].id,
        conversationId: data.id,
      });
      commit(types.SET_CHAT_DATA_FETCHED);  // ← proper Vuex mutation
    } catch (error) {}
  }
},
```

**4. Preserve `dataFetched` in `UPDATE_CONVERSATION`** in `index.js`:
```js
const newConversation = { ...selectedConversation, ...updates };
if (selectedConversation.dataFetched !== undefined) {
  newConversation.dataFetched = selectedConversation.dataFetched;
}
if (selectedConversation.allMessagesLoaded !== undefined) {
  newConversation.allMessagesLoaded = selectedConversation.allMessagesLoaded;
}
allConversations[index] = newConversation;
```

Note: `SET_ALL_CONVERSATION` already preserves these properties for the selected chat, but `UPDATE_CONVERSATION` does not — this inconsistency is what makes the bug possible.

### To Reproduce

1. Open a conversation in Chatwoot
2. While the initial messages are loading (during the async fetchPreviousMessages in setActiveChat), have a WebSocket event arrive for that conversation (e.g., another agent changes the conversation status, or a bot updates the conversation)
3. The UPDATE_CONVERSATION mutation fires, replacing the conversation object in the store
4. dataFetched is set on the old, orphaned object reference
5. Scroll up — infinite spinner appears, no HTTP request is fired

The bug is a race condition and not deterministic, but it is more likely to occur on:
- Conversations with frequent WebSocket updates (status changes, resolved/reopened cycles, bot activity)
- Conversations opened while there is active agent/bot activity

To verify the bug is active, run in browser console:
```js
const store = document.querySelector('#app').__vue_app__.config.globalProperties.$store;
const conv = store.state.conversations.allConversations.find(c => c.id === CONVERSATION_ID);
console.log(conv.dataFetched); // Will show: undefined (should be: true)
```

### Expected behavior

Scrolling up should always trigger an HTTP request to fetch older messages when allMessagesLoaded is false, regardless of whether WebSocket events arrived during initial load.

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 24 (Docker Swarm host). Bug affects all client OS — it is a server-delivered frontend race condition.

### Browser and version

All browsers affected (confirmed on Chrome latest). The bug is in the Vue/Vuex state management, not browser-specific.

### Docker (if applicable)

Docker version 27.x, Docker Swarm mode (single node)
Image: Chatwoot 4.10.1

### Additional context

- This is the root cause of #10373, which was closed as "not planned" due to insufficient diagnosis at the time
- The `SET_ALL_CONVERSATION` mutation already preserves `dataFetched` for the selected chat, but `UPDATE_CONVERSATION` does not — this inconsistency is what makes the bug possible
- This is a textbook Vuex anti-pattern: mutating state outside of mutations after an async operation
- The bug affects all channels and conversation sizes (confirmed on WhatsApp conversations with ~20 messages)
- We are happy to submit a PR with the fix if the team agrees with the approach

**Files affected:**
- `app/javascript/dashboard/store/modules/conversations/actions.js`
- `app/javascript/dashboard/store/modules/conversations/index.js`
- `app/javascript/dashboard/store/mutation-types.js`

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description

Ref: https://github.com/chatwoot/chatwoot/issues/13444#issue-3896381902

Fixes https://github.com/chatwoot/chatwoot/issues/13444

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by scmmishra** [comment]
@codex please review

File: app/javascript/dashboard/store/modules/conversations/index.js
Comment (scmmishra) [inline app/javascript/dashboard/store/modules/conversations/index.js:1]: @iamsivin The `SET_ALL_MESSAGES_LOADED` and `CLEAR_ALL_MESSAGES_LOADED` mutations use `getSelectedChatConversation(_state)` which is selectedChatId-based, not ID-based. This is a bug we solved by passing the `conversationId` inside `SET_CHAT_DATA_FETCHED`. See if we can fix that too

File: app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js [hunk 1]
```diff
@@ -570,6 +570,50 @@ describe('#mutations', () => {
...
+      expect(state.allConversations[1].dataFetched).toBeUndefined();
+    });
+
+    it('should do nothing if conversation is not found', () => {
+      const state = { allConversations: [{ id: 1 }] };
+      mutations[types.SET_CHAT_DATA_FETCHED](state, 999);
+      expect(state.allConversations[0].dataFetched).toBeUndefined();
+    });
+
+    it('should survive the race: SET_ALL_CONVERSATION replaces the object, then SET_CHAT_DATA_FETCHED still works', () => {
```
Comment (scmmishra) [inline app/javascript/dashboard/store/modules/specs/conversations/mutations.spec.js:589]: Let's add a case for `UPDATE_CONVERSATION` also, since that is where the original race condition was reported

**Review by scmmishra — CHANGES_REQUESTED** [review]

**Comment by iamsivin** [comment]
@codex review

**Review by scmmishra — APPROVED** [review]
