### PR TITLE
fix duplicate messages on repeating enter button press on slow network

### LINKED ISSUE #946: Duplicate messages if I repeatedly press enter button
- Duplicate messages are sent if the network is slow and I repeatedly press enter on the reply box

### PR DESCRIPTION
**Pull request by neymarsabin**
# Pull Request Template

## Fix duplicate messages on repeating enter button press on a slow network

After Enter button press copy message to a new variable and clear up the message input.

Fixes #946 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Added sleep(10) in create action of this /API/v1/accounts/conversations/messages_controller.rb
- Checked in UI with multiple enter button press, only one request is sent to create the message to API and then the input field is cleared.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue [hunk 1]
```diff
@@ -211,18 +211,19 @@ export default {
       if (this.message.length > this.maxLength) {
         return;
       }
+      const newMessage = this.message;
+      this.clearMessage();
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue:216]: This should be inside the check for canned response list. Otherwise `/` commands for canned response will not work.
Screenshot 2020-06-28 at 6 55 31 PM

**Comment by neymarsabin** [comment]
@pranavrajs I made the change, but I am not sure what failed in CircleCI.

File: db/seeds.rb [hunk 2]
```diff
@@ -35,3 +35,4 @@
   additional_attributes: {}
 )
 Message.create!(content: 'Hello', account: account, inbox: inbox, conversation: conversation, message_type: :incoming)
+CannedResponse.create!(account: account, short_code: 'start', content: 'Hello welcome to chatwoot.')
```
Comment (pranavrajs) [inline db/seeds.rb:38]: 👍
