### PR TITLE
fix: validations for whatsapp templates with no params

### LINKED ISSUE #4819: Whatsapp templates - Handle no variable templates
Remove validation for tempaltes which dont have tempaltes

### PR DESCRIPTION
**Pull request by fayazara**
# Pull Request Template

## Description

Removes validation for whatsapp templates with no variables

Fixes #4819 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Created a mock template with no variables and sent the payload through

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue [hunk 1]
```diff
@@ -43,8 +41,6 @@
 </template>
 
 <script>
-import { required } from 'vuelidate/lib/validators';
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue:46]: `requiredIf` is better instead of removing the required condition altogether, right?

**Review by iamsivin — APPROVED** [review]
Code LGTM 👍🏻

File: app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+Vue.use(Vuelidate);
+
+import i18n from 'dashboard/i18n';
+
+localVue.use(VueI18n);
+// localVue.component('woot-button', WootButton);
+// localVue.component('woot-input', WootInput);
+
+const i18nConfig = new VueI18n({
+  locale: 'en',
```
Comment (pranavrajs) [inline app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js:20]: Please remove these as well.

File: app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+  messages: i18n,
+});
+
+describe('whatsappTemplates', () => {
```
Comment (pranavrajs) [inline app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js:24]:
```suggestion
describe('#WhatsAppTemplates', () => {
```

**Review by pranavrajs — CHANGES_REQUESTED** [review]
I have minor suggestions, please take a look.

File: app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js [hunk 4]
```diff
@@ -0,0 +1,81 @@
+import TemplateParser from '../../../../dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue';
+import { mount, createLocalVue } from '@vue/test-utils';
+import { templates } from './fixtures';
+const localVue = createLocalVue();
+import VueI18n from 'vue-i18n';
+import Vue from 'vue';
+// import WootButton from 'dashboard/components/ui/WootButton';
+// import WootInput from '../../../../widget/components/Form/Input.vue';
+
```
[the remark this answers is not in the document]
Comment (fayazara) [reply app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js:9]: These were added by mistake, removing them

**Comment by fayazara** [comment]
> I have minor suggestions, please take a look.

@pranavrajs Updated.

**Review by pranavrajs — APPROVED** [review]
