### PR TITLE
Fixes: Dropdown width issue fixes by using fit-content

### LINKED ISSUE #2043: Enhancement: Make dropdown component to fit content
- Right now it depends on fixed width, Ideal case is to have max-width on dropdown--pane and fit content for dropdown 
image

### PR DESCRIPTION
**Pull request by sivin-git**
FIxes #2043

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/MoreActions.vue [hunk 1]
```diff
@@ -118,7 +118,7 @@ export default {
 .dropdown-pane {
   right: -12px;
   top: 48px;
-  width: auto;
+  width: fit-content;
```
Comment (nithindavid) [inline app/javascript/dashboard/components/widgets/conversation/MoreActions.vue:121]: This needs to go in the woot-dropdown-menu component styles

**Review by nithindavid — CHANGES_REQUESTED** [review]

File: app/javascript/dashboard/components/layout/AvailabilityStatus.vue [hunk 2]
```diff
@@ -170,6 +170,7 @@ export default {
 .status-change {
   .dropdown-pane {
     top: -132px;
+    width: 80%;
```
Comment (nithindavid) [inline app/javascript/dashboard/components/layout/AvailabilityStatus.vue:173]: Since we already have fit-content, Do we really need this?

**Review by nithindavid — CHANGES_REQUESTED** [review]
Please see the comment.

**Review by nithindavid — APPROVED** [review]
