### PR TITLE
fixes: New message created does not auto-scroll to the bottom

### LINKED ISSUE #3727: Bug: posting a reply to a long chat does not auto scroll to the bottom
As the title says, when posting a reply to a long chat, it does not auto scroll me to the bottom of the page to see the latest reply i just posted. This is after my update from 1.2.2 to 2.0.2

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3727 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Can be tested by sending messages to a chat

**Screen recording**

**Before** 

https://user-images.githubusercontent.com/64252451/149445814-aae58f45-d166-4db3-9fac-e018bbc69215.mov

**After**

https://user-images.githubusercontent.com/64252451/154194473-a3cff994-b673-40ba-834b-6bed917b597c.mov

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/MessagesView.vue [hunk 1]
```diff
@@ -263,32 +261,29 @@ export default {
...
+    bus.$on(BUS_EVENTS.SET_TWEET_REPLY, this.setSelectedTweet);
   },
 
   beforeDestroy() {
     this.removeBusListeners();
-    this.removeScrollListener();
   },
 
   methods: {
+    scrollToEndOfMessages() {
```
Comment (nithindavid) [inline app/javascript/dashboard/components/widgets/conversation/MessagesView.vue:277]: There would be couple of side effects with this. Can you cross check the current behaviour with

1. When agent is reading a message and visitor replies or a new activity comes in, it would scroll automatically to end interfering the agents reading experience 

2. When is conversation is scrolled up to load previous message, would it come to end ?

**Review by nithindavid — CHANGES_REQUESTED** [review]
Please see the functional comment?

**Comment by iamsivin** [comment]
> Please see the functional comment?

Looking into it.

**Comment by pranavrajs** [comment]
@nithindavid Can you please pair with the @iamsivin to get this merged?

**Review by pranavrajs — APPROVED** [review]
