### PR TITLE
fix: Ensure Automation rule executions are account scoped

### LINKED ISSUE #605: Unauthorized after creating account
**Describe the bug**
My password is not saved correctly. I can't log back in.
**To Reproduce**
I deployed using Heroku. Changed my password and I confirmed I received a `200`. Logged out and when trying to log back in I receive 401.
**Expected behavior**
To be able to log in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] chrome

image
image

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

This is one possible fix to tackle with cached automation rules when automation gets called on two different accounts with the same event name.

Fixes [#605](https://github.com/chatwoot/product/issues/605)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

-

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/listeners/automation_rule_listener.rb [hunk 1]
```diff
@@ -8,6 +8,8 @@ def conversation_updated(event_obj)
 
     return unless rule_present?('conversation_updated', account)
 
+    @rules = current_account_rules('conversation_updated', account)
```
Comment (sojan-official) [inline app/listeners/automation_rule_listener.rb:11]: we don't need to memoize this right ? 
let's do 
```
rule = current_account_rules('conversation_updated', account) 
  @rules.each do |rule|
      conditions_match = ::AutomationRules::ConditionsFilterService.new(rule, conversation, { changed_attributes: changed_attributes }).perform
      AutomationRules::ActionService.new(rule, account, conversation).perform if conditions_match.present?
    end
```

File: spec/listeners/automation_rule_listener_spec.rb [hunk 2]
```diff
@@ -644,4 +644,48 @@
...
+
+    it 'triggers automation at the same time' do
+      new_conversation = new_account.conversations.last
+      new_automation_rule = new_account.automation_rules.last
+
+      event = Events::Base.new('conversation_created', Time.zone.now, { conversation: conversation })
+      new_event = Events::Base.new('conversation_created', Time.zone.now, { conversation: new_conversation })
+
+      listener.conversation_created(event)
+      listener.conversation_created(new_event)
```
Comment (tejaswinichile) [inline spec/listeners/automation_rule_listener_spec.rb:679]: @sojan-official As per our discussion, I have added two events with the same condition for different accounts and checked if the message is being created in a separate conversation with the respective automation rule id.
