### PR TITLE
fix: unassign team activity message

### LINKED ISSUE #5911: `Bulk Assign to Team - None` creates invalid activity message
Last week, we shipped https://github.com/chatwoot/chatwoot/pull/5885, and the assignment, and un-assignment worked properly. However, there is an issue with the activity messages generated in the UI.

Screenshot 2022-11-21 at 1 19 26 PM

The second message in the screenshot is generated if I use the bulk assign team - none option. The fourth message shows how it looks like if I use the sidebar to unassign the team.

To reproduce:

- Select a conversation from the list, assign team to none.

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

 unassign team activity message

Fixes #5911 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

https://user-images.githubusercontent.com/10827585/204370830-0c600536-9e1e-4249-b45f-9523af42a658.mov

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/models/concerns/activity_message_handler.rb [hunk 1]
```diff
@@ -73,7 +73,8 @@ def create_unmuted_message
   end
 
   def generate_team_change_activity_key
-    key = team_id ? 'assigned' : 'removed'
+    team = Team.find_by(id: team_id)
+    key = team.present? ? 'assigned' : 'removed'
```
Comment (pranavrajs) [inline app/models/concerns/activity_message_handler.rb:77]: Looks good, can we add a spec to cover this case?

**Review by muhsin-k — APPROVED** [review]
