### PR TITLE
Fix error messages during login for non-verified users

### LINKED ISSUE #1915: Wrong error message when login fails for non activated accounts
**Describe the bug**

When I try to re-login into an account after logging out without activating the account via an email, it fails with a confusing error message.

**To Reproduce**

1. Signup with a dummy account and go to dashboard but don't activate your account via email auth.
2. Logout of the account
3. Try to login again.
4. You see a "bad password" error message.

**Expected behavior**
The error message should be
```
A confirmation email was sent to your account at 'myemail@mydomain.com'. You must follow the instructions in the email before your account can be activated
```

**Screenshots**

N/A

**Browser logs**

```
Request URL: https://app.chatwoot.com/auth/sign_in
Request Method: POST
Status Code: 401 Unauthorized
Remote Address: 3.224.159.100:443
Referrer Policy: strict-origin-when-cross-origin
Response: {"success":false,"errors":["A confirmation email was sent to your account at 'account1@asdf.com'. You must follow the instructions in the email before your account can be activated"]}
  ```

**Server logs**

NA

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku): app.chatwoot.com

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Any
 - Browser [e.g. chrome, safari]  Any
 - Version [e.g. 22] Latest

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by srameshr**
# Pull Request Template

## Description

Fix error messages during login for non-verified users

Fixes #1915

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Local + tests

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/routes/login/Login.vue [hunk 1]
```diff
@@ -149,7 +149,17 @@ export default {
           }
 
           if (response && response.status === 401) {
-            this.showAlert(this.$t('LOGIN.API.UNAUTH'));
+						const { errors } = response.data;
+            if (
+              errors &&
```
Comment (nithindavid) [inline app/javascript/dashboard/routes/login/Login.vue:154]: Move this to a variable since more than 3 conditions are used

**Review by nithindavid — CHANGES_REQUESTED** [review]

File: app/javascript/dashboard/routes/login/Login.vue (hunk 1 above)
Comment (srameshr) [reply app/javascript/dashboard/routes/login/Login.vue]: Yeah, done.
So, can I know if you are planning the hotfix release in the new few hours? If 1.14.0 broke a feature like inbox_email it should be a priority for the hotfix to go out ASAP right?

**Review by nithindavid — APPROVED** [review]
