### PR TITLE
fix: Yellow color shades are inconsistent

### LINKED ISSUE #4365: Yellow color shades are inconsistent
After merging #4334, the yellow colors got changed and the colors are inconsistent in some places. Please see the following cases

1. Availability status should have a light shade, now it is seen in darker shade.
Screenshot 2022-04-04 at 10 52 15 AM

2. Snooze until, user session not verified texts used a lighter shade to indicate warning, but it got updated.
Screenshot 2022-04-04 at 10 52 29 AM

### PR DESCRIPTION
**Pull request by nithindavid**
Fixes #4365

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/Thumbnail.vue [hunk 1]
```diff
@@ -209,7 +209,7 @@ export default {
   }
 
   .user-online-status--busy {
-    background: var(--y-700);
+    background: var(--y-500);
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/Thumbnail.vue:212]: This color is not consistent with the color in AvailabilityStatusComponent

**Comment by nithindavid** [comment]
@pranavrajs closing this as changes are already merged with another PR.

**Review by pranavrajs — APPROVED** [review]

**Review by iamsivin — APPROVED** [review]
LGTM 👍🏻
