### PR TITLE
fix: Check uploaded file size in widget and dashboard

### LINKED ISSUE #1974: Widget and dashboard not validating file size on uploads
- Set max file size in constants
- Add file size check in both widget and dashboard
- Add  file size check in file upload API

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #1974 
**Preview**
Screenshot 2021-03-23 at 1 51 37 PM

### CODE REVIEW

File: app/javascript/widget/views/Home.vue [hunk 1]
```diff
@@ -154,6 +167,14 @@ export default {
       );
     },
   },
+  mounted() {
+    bus.$on('on-attachment-error', () => {
```
Comment (pranavrajs) [inline app/javascript/widget/views/Home.vue:171]: I would suggest keeping this name as a constant in a separate file if possible so that we know about all the events we are emitting in one place.

File: app/javascript/widget/views/Home.vue [hunk 2]
```diff
@@ -221,5 +242,13 @@ export default {
   .input-wrap {
     padding: 0 $space-normal;
   }
+  .banner {
+    background: $color-error;
+    color: $color-white;
+    font-size: $font-size-default;
+    font-weight: $font-weight-bold;
+    padding: $space-slab;
```
Comment (pranavrajs) [inline app/javascript/widget/views/Home.vue:250]: Can't we use the CSS variable here?

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Nice work! 🎉

Overall the changes look nice. Please fix the individual comments on the PR.

**Comment by muhsin-k** [comment]
@pranavrajs Please check the latest changes

File: app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue [hunk 3]
```diff
@@ -351,21 +355,30 @@ export default {
       }
     },
     onFileUpload(file) {
-      this.attachedFiles = [];
-      if (!file) {
-        return;
+      if (file) {
+        if (checkFileSizeLimit(file, MAXIMUM_FILE_UPLOAD_SIZE)) {
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue:359]: Please combine this with the previous line.

File: app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue [hunk 4]
```diff
@@ -351,21 +355,30 @@ export default {
...
+          this.attachedFiles = [];
+          if (!file) {
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue:361]: This check is not required if you are checking the existence of the file at the beginning of the function.

**Comment by muhsin-k** [comment]
@pranavrajs Changes are updated as per code review

**Review by pranavrajs — APPROVED** [review]
Looks good! @nithindavid / @sojan-official Can you please do a QA here?

@muhsin-k Could you please write down the steps for QA?

**Comment by muhsin-k** [comment]
@nithindavid / @sojan-official 

**Widget**
- Try uploading a file with a size of more than 40MB
- Expected result - Shows a banner message "File exceeds the 40MB attachment limit"

**Dashboard**
- Try uploading a file with a size of more than 40MB 
- Expected result-Shows a toast alert "File exceeds the 40MB attachment limit"
