### PR TITLE
fixes: Agent name in Twitter channel private note acts as a link

### LINKED ISSUE #3945: bug: Clicking the agent name in private note it acts as a link
**Describe the bug**

In a Twitter channel conversation, the agent name mentioned in a private note acts as a link and opens in a new tab.

**To Reproduce**

1. Go to the Twitter channel and open a conversation.
2. Click private note and send a message tagging someone.
3. Now you can see the color issue mentioned in #3887
4. And click on the mentioned name it will open a new tab with a link like ‘www.twitter.com/name’

**Expected behavior**

By clicking the agent name in a private note no need to do any action.

**Solution**

In the Twitter channel, the agent name mentioned in a private note is showing inside, `<a>` tag which should in `<span>` same as other channels by this will solves color issue also.

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3945 & #3887 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

**Before**

image

**After**

Screenshot 2022-03-29 at 6 01 30 PM

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/shared/helpers/MessageFormatter.js [hunk 1]
```diff
@@ -13,8 +13,9 @@ const TWITTER_HASH_REPLACEMENT =
 const USER_MENTIONS_REGEX = /mention:\/\/(user|team)\/(\d+)\/(.+)/gm;
 
 class MessageFormatter {
-  constructor(message, isATweet = false) {
+  constructor(message, isAPrivateNote = false, isATweet = false) {
```
Comment (pranavrajs) [inline app/javascript/shared/helpers/MessageFormatter.js:16]: Screenshot 2022-03-29 at 7 02 02 PM



@iamsivin Let us keep the new attribute to last. Keep the existing so that the rest of the implementation is not affected.

File: app/javascript/shared/helpers/specs/MessageFormatter.spec.js [hunk 2]
```diff
@@ -36,14 +36,18 @@ describe('#MessageFormatter', () => {
...
+        new MessageFormatter(message, false, true).formattedMessage
+      ).toMatch(
         '<p><a href="http://twitter.com/chatwootapp" target="_blank" rel="noreferrer nofollow noopener">@chatwootapp</a> is an opensource tool thanks @longnonexistenttwitterusername</p>'
       );
     });
 
     it('should add links to #tags', () => {
       const message = '#chatwootapp is an opensource tool';
-      expect(new MessageFormatter(message, true).formattedMessage).toMatch(
+      expect(
```
Comment (pranavrajs) [inline app/javascript/shared/helpers/specs/MessageFormatter.spec.js:48]: Please add a test case for the new condition.

File: app/javascript/shared/helpers/MessageFormatter.js (hunk 1 above)
Comment (iamsivin) [reply app/javascript/shared/helpers/MessageFormatter.js]: Done

File: app/javascript/shared/helpers/specs/MessageFormatter.spec.js (hunk 2 above)
Comment (iamsivin) [reply app/javascript/shared/helpers/specs/MessageFormatter.spec.js:48]: Done https://github.com/chatwoot/chatwoot/pull/4326/commits/3d8598b87489798ea4041ecb7a881099d3461e53
