### PR TITLE
fix: Hide deleted messages on widget side

### LINKED ISSUE #2584: bug: Attachments are showing after deleting a message
https://user-images.githubusercontent.com/12408980/124720966-50116280-df26-11eb-8869-918618dfb84f.mov

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #2584 and #2586

### CODE REVIEW

**Comment by pranavrajs** [comment]
As per the conversation we had at https://github.com/chatwoot/chatwoot/issues/2586#issuecomment-875594747, we could completely hide the bubble if the message is deleted.

**Comment by muhsin-k** [comment]
> As per the conversation we had at [#2586 (comment)](https://github.com/chatwoot/chatwoot/issues/2586#issuecomment-875594747), we could completely hide the bubble if the message is deleted.

@pranavrajs That makes sense. I will update the PR accordingly

File: app/javascript/widget/mixins/messageMixin.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+export default {
```
Comment (nithindavid) [inline app/javascript/widget/mixins/messageMixin.js:1]: Nice work 🎉

**Review by nithindavid — APPROVED** [review]
