### PR TITLE
Bug: Instagram render template message twice

### LINKED ISSUE #3196: Instagram account conversation triggers welcome message twice
If a new conversation is created in Instagram account inboxes, then the welcome message is triggered twice. However, it is sent only once to the sender.

| Dashboard view | Instagram sender view |
| -- | -- |
| Screenshot 2021-10-11 at 1 51 33 PM |  translate |

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

When we send a welcome message to the Instagram user that message comes back again to save it in the Chatwoot inbox, we should consider a template message as a repeated message and neglect that.

Fixes #3196 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested on staging

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
This is how it was looking before
Screenshot 2021-11-02 at 4 11 06 PM
>

**Comment by sojan-official** [comment]
@tejaswinichile  While looking into the code, I just noticed that we are handling the way messages are being sent to Facebook and Instagram differently. 

For facebook -> send the message and update the message-id to the source id 
https://github.com/chatwoot/chatwoot/blob/03b1a3d045bbfc221bcf07c8155eccd2d0d88905/app/services/facebook/send_on_facebook_service.rb#L19

for Instagram, -> sending the message without storing the source id. 
https://github.com/chatwoot/chatwoot/blob/03b1a3d045bbfc221bcf07c8155eccd2d0d88905/app/services/instagram/send_on_instagram_service.rb#L60

I think if possible, we should have the message updated with the Instagram message Id as well. This will let us handle the echo message better. We can check whether we already have a matching message with the particular source id before creating a new message.  

The content scan logic we have at the moment might break in cases where an agent replied same message body from chatwoot dashboard as well directly from facebook or Instagram.  Chatwoot would only create a single message with this case instead of creating two ?

Also the source id will ensure that we can show a sent status for that particular message more reliably

**Comment by tejaswinichile** [comment]
@sojan-official When I checked it last time because I wanted to handle it in the same way in Facebook update, but in Instagram it wasn't returning any message-id let me confirm it again.

**Comment by tejaswinichile** [comment]
@sojan-official I just got it, I didn't do it because the message id was not available for message reaction. As we are not handling message reaction right now I have added message-id changes to check the duplicate message.

File: app/builders/messages/instagram/message_builder.rb [hunk 1]
```diff
@@ -103,7 +107,7 @@ def message_params
       account_id: conversation.account_id,
       inbox_id: conversation.inbox_id,
       message_type: message_type,
-      source_id: message_source_id,
+      source_id: message_indentifier,
```
Comment (pranavrajs) [inline app/builders/messages/instagram/message_builder.rb:110]: identifier?

**Review by pranavrajs — COMMENTED** [review]
Looks like there is a typo in the method name.

File: app/builders/messages/instagram/message_builder.rb (hunk 1 above)
Comment (tejaswinichile) [reply app/builders/messages/instagram/message_builder.rb:110]: Took some time to realize that.

File: app/builders/messages/instagram/message_builder.rb [hunk 2]
```diff
@@ -112,12 +116,9 @@ def message_params
...
     cw_message = conversation.messages.where(
-      source_id: nil,
-      message_type: 'outgoing',
-      content: message_content,
-      private: false,
-      status: :sent
+      source_id: @messaging[:message][:mid]
     ).first
+
     cw_message.update(content_attributes: content_attributes) if cw_message.present?
```
Comment (sojan-official) [inline app/builders/messages/instagram/message_builder.rb:122]: Is updating the content_attributes of the message intentional? Could we add a comment here on why we need to do this?

Comment (tejaswinichile) [reply app/builders/messages/instagram/message_builder.rb:122]: It's not necessary now since we are storing the same in the message source id.
Removing the same.

**Review by sojan-official — APPROVED** [review]
