### PR TITLE
chore: fixes no gutter space between settings page content and right …

### LINKED ISSUE #2478: No gutter space between settings page content and right content sidebar

### PR DESCRIPTION
**Pull request by iamsivin**
Fixes #2478

### CODE REVIEW

File: app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue [hunk 1]
```diff
@@ -246,3 +246,8 @@ export default {
   },
 };
 </script>
+<style lang="scss" scoped>
+.content-spacing {
```
Comment (pranavrajs) [inline app/javascript/dashboard/routes/dashboard/settings/agents/Index.vue:250]: @iamsivin This style is repeated in every component which is not required. Please move this to a common stylesheet.

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Please see the inline comment.

**Review by pranavrajs — APPROVED** [review]

**Review by nithindavid — APPROVED** [review]
