### PR TITLE
Fix: Find mailbox with cc email

### LINKED ISSUE #4151: Email Channel Issues
- [x] Duplicate emails are appearing in the conversation
- [x] If the inbox is in cc, the emails are not appearing in Chatwoot.

----

- [x] cc Emails in the input box are not taken into consideration.
- [x] Mails don't get deleted.

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

> Added email box finder with cc email
> Ignore duplicate emails with same message-id

Fixes #4151 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Test cases.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@sojan-official @aswindevps  Please have a look, we are making sure if someone sends an email with chatwoot inbox email in the CC we should still receive that email in our inbox.

File: app/mailboxes/application_mailbox.rb [hunk 1]
```diff
@@ -21,17 +21,41 @@ def self.reply_mail?
...
+    inbound_mail_obj.mail.cc&.each do |email|
+      channel = Channel::Email.find_by('lower(email) = ? OR lower(forward_to_email) = ?', email.downcase, email.downcase)
+      if channel.present?
+        is_a_support_email = true
+        break
+      end
+    end
+
+    is_a_support_email
+  end
```
Comment (sojan-official) [inline app/mailboxes/application_mailbox.rb:57]: can we have a single method instead of both these methods, which accepts the argument of an email array instead of inbound_mail_obj?  Since the logic seems to be repetitive

File: app/mailboxes/support_mailbox.rb [hunk 2]
```diff
@@ -21,13 +21,26 @@ def process
...
-    raise 'Email channel/inbox not found' if @channel.nil?
+  end
 
-    @channel
+  def find_channel_with_to_mail
+    mail.to.each do |email|
+      @channel = Channel::Email.find_by('lower(email) = ? OR lower(forward_to_email) = ?', email.downcase, email.downcase)
+      break if @channel.present?
+    end
   end
```
Comment (sojan-official) [inline app/mailboxes/support_mailbox.rb:44]: similar comment as above.  We could move the logic into an `EmailChannelFinder` in `app/finders` i guess. 
so that the chances of people missing out `'lower(email) = ? OR lower(forward_to_email) = ?'` is reduced.

**Review by sojan-official — COMMENTED** [review]
The code looks good. But some minor comments on improving maintainability.

**Review by sojan-official — COMMENTED** [review]
can we also add a spec for the finder ?
- with uppercase as well lower case emails

**Comment by tejaswinichile** [comment]
@sojan-official Oh yes let me do it.

**Comment by tejaswinichile** [comment]
cc email
cc test email


CC email with a forwarder email address and email channel address.

**Comment by tejaswinichile** [comment]
@sojan-official Please have a look.
