### PR TITLE
Fix: text overlaps in contact name

### LINKED ISSUE #1710: Bug: Text overlaps in conversation area
**Describe the bug**

Time of the message overlaps in conversation area with channel name
 
**To Reproduce**

1. Send a conversation through any channel
2. Visit Dashboard immediately
3. Check the conversation area

**Expected behavior**

Text should not be overlap. Instead of `less than a minute ago` may be we can use `just now`

**Screenshots**

Chatwoot

**Environment**

Self hosted development branch 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Chrome
 - Version:88.0.4324.96 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by pranjal0819**
## Description

Add width in contact name to prevent the overflow of text.

Fixes #1710 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
1. image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pranjal0819** [comment]
cc @sladyn98

**Comment by sladyn98** [comment]
CC @sojan-official @nithindavid

File: app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue [hunk 1]
```diff
@@ -8,8 +8,8 @@
         :username="currentContact.name"
         :status="currentContact.availability_status"
       />
-      <div class="user--profile__meta">
-        <h3 class="user--name text-truncate">
+      <div class="user--profile__meta" style="max-width: 40rem">
```
Comment (nithindavid) [inline app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue:11]: Please avoid inline styles. I think we can move these to the `<style>` tag at the bottom of the file, which is scoped to load only for this file.

Comment (nithindavid) [reply app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue:11]: Also please make sure the `40rem` will not break on small screen devices.

File: app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue [hunk 2]
```diff
@@ -80,7 +80,10 @@ export default {
                 status={row.availability_status}
               />
               <div>
-                <h6 class="sub-block-title user-name text-truncate">
+                <h6
+                  class="sub-block-title user-name text-truncate"
+                  style="width: 215px"
```
Comment (nithindavid) [inline app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue:85]: We follow `rem` for hard coded width, please move to `style` and use `rem` instead of `px`

**Review by nithindavid — CHANGES_REQUESTED** [review]

**Comment by nithindavid** [comment]
@pranjal0819 Thanks for the PR, Please go through the comments :)

File: app/javascript/dashboard/assets/scss/widgets/_conv-header.scss [hunk 3]
```diff
@@ -56,6 +56,19 @@ $resolve-button-width: 13.2rem;
       flex-direction: column;
       justify-content: center;
       margin-left: $space-slab;
+      max-width: 50rem;
+
+      @media screen and (max-width: 1600px) {
```
Comment (nithindavid) [inline app/javascript/dashboard/assets/scss/widgets/_conv-header.scss:61]: We have mixins for responsive sizes. Please see this file `components/widgets/conversation/ConversationBox.vue`.

File: app/javascript/dashboard/assets/scss/widgets/_conv-header.scss [hunk 4]
```diff
@@ -56,6 +56,19 @@ $resolve-button-width: 13.2rem;
       flex-direction: column;
       justify-content: center;
       margin-left: $space-slab;
+      max-width: 20rem;
```
Comment (iamsivin) [inline app/javascript/dashboard/assets/scss/widgets/_conv-header.scss:59]: Instead of using fixed-width, can we use flex to do the same.  I have created a rough commit for your reference. Please see if this works.

https://github.com/chatwoot/chatwoot/commit/914a32a5255bee9a33e54ca1ea59e0d87889f7c7

**Comment by iamsivin** [comment]
@pranjal0819  Any update on this, let me know if you are not planning to work on this.

**Comment by sladyn98** [comment]
@pranjal0819 Can you add the fix so that they can merge it ?

**Comment by pranjal0819** [comment]
> @pranjal0819 Any update on this, let me know if you are not planning to work on this.

I will update it today

File: app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue [hunk 5]
```diff
@@ -142,10 +142,21 @@ export default {
...
-  text-overflow: ellipsis;
+.user {
+  min-width: 0;
+  margin-right: var(--space-normal);
+
+  .user--profile__meta {
+    min-width: 0;
+  }
+
+  .text-truncate {
```
Comment (nithindavid) [inline app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue:153]: This text-truncate class here is already defined as a utility class, we remove the repeating styles.
```suggestion
  .user--name {
    width: 100%;
  }
```

File: app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue [hunk 6]
```diff
@@ -233,6 +233,7 @@ export default {
       font-size: var(--font-size-small);
       margin: 0;
       text-transform: capitalize;
+      width: 22rem;
```
Comment (nithindavid) [inline app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue:236]: This is not needed as this already fixed in another pr

**Review by nithindavid — CHANGES_REQUESTED** [review]
@pranjal0819 Thanks for the work :) Just a minor change and we are good to merge

**Comment by nithindavid** [comment]
@pranjal0819 Let me know if you're working on this. Else I'll fix this from my side and will merge it.

**Review by nithindavid — APPROVED** [review]
