### PR TITLE
fixed slack channel builder so that the channel list can have more th…

### LINKED ISSUE #1549: Can't receive message on slack side, undefined method `id`
Hello, I just deployed chatwoot on my k8s cluster. I setup the slack integration but no message came out. I checked the log and it says 

> E, [2020-12-24T10:26:06.375546 #1] ERROR -- : Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"zV2vfiwKMgbQZ18tXCJhULDw\"}", "data"=>"{\"action\":\"update_presence\"}"}) [NoMethodError - undefined method `id' for nil:NilClass]: /app/app/channels/room_channel.rb:29:in `update_subscription' | /app/app/channels/room_channel.rb:11:in `update_presence' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:270:in `public_send' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:270:in `dispatch_action' | /gems/ruby/2.7.0/gems/actioncable-6.0.3.4/lib/action_cable/channel/base.rb:170:in `block in perform_action'

Can anyone help me with this error?

### PR DESCRIPTION
**Pull request by lgezyxr**
…an 100 elements

# Pull Request Template

## Description

The current slack channel builder will use slack_client.conversations_list to get the conversation list of slack workspace. But the slack API only returns 100 conversations by default. So I made a loop and use the next_cursor parameter to make sure we could get all the conversations of the workspace.

Fixes #1549

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I deployed this on my working environment and tested on the company's slack and it works.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/integrations/slack/channel_builder.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def slack_client
   def find_or_create_channel
     current_list = slack_client.conversations_list
     channels = current_list.channels
-    while current_list.response_metadata.next_cursor
+    while !current_list.response_metadata.next_cursor.empty?
```
Comment (pranavrajs) [inline lib/integrations/slack/channel_builder.rb:26]: Can we use `.present?` now?

Comment (lgezyxr) [reply lib/integrations/slack/channel_builder.rb]: Thanks, I've changed that to .present?

**Review by sojan-official — APPROVED** [review]

**Comment by sojan-official** [comment]
@lgezyxr Thanks a lot for the changes.
