### PR TITLE
fix:  Unread notification count in multiple accounts

### LINKED ISSUE #4367: The notification count is wrong in the realtime-notification update
The real-time notification update is returning the total number of notifications if the user has more than one accounts. It should only return the number of notifications in the current account.

**The problem:**

Screenshot 2022-04-04 at 11 34 46 AM

As seen here the notifications for the user in account 1 is 7, but when a new notification is created, the bell icon would show 14.

**Todo:**

- [ ] Send the only number of notifications in the account where notification is created.

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #4367

### CODE REVIEW

**Review by sojan-official — APPROVED** [review]

File: app/models/user.rb [hunk 1]
```diff
@@ -188,10 +188,10 @@ def will_save_change_to_email?
     mutations_from_database.changed?('email')
   end
 
-  def notifications_meta
+  def notifications_meta(account_id)
     {
-      unread_count: notifications.where(read_at: nil).count,
-      count: notifications.count
+      unread_count: notifications.where(account_id: account_id, read_at: nil).count,
```
Comment (pranavrajs) [inline app/models/user.rb:193]: @muhsin-k @sojan-official Can we add a test case for the same?
