### PR TITLE
fix: Disable "none" option from team dropdown If team is not selected 

### LINKED ISSUE #2817: Disable "none" option from assign team dropdown If the team is not selected
https://user-images.githubusercontent.com/12408980/129442871-1f1e6dd1-54cb-49da-aa06-7afa98f6232d.mov

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #2817

### CODE REVIEW

File: app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue [hunk 1]
```diff
@@ -232,7 +231,17 @@ export default {
...
+        ...(this.assignedTeam
+          ? [
+              {
+                id: 0,
+                name: 'None',
+              },
+            ]
+          : []),
+        ...this.teams,
+      ];
```
Comment (pranavrajs) [inline app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue:244]: This is hard to read. I guess a normal if else case would be better.

**Review by iamsivin — APPROVED** [review]
