### PR TITLE
enhancement: Profile settings accessibility improvements

### LINKED ISSUE #2053: bug: Unable to update profile details without filling change password form values
**How to reproduce?**
1. Go to the profile settings page
2. Change the display name
3. Press "Update profile"
4. It will show an error "Confirm password should match the password"

**Preview**
Screenshot 2021-04-05 at 8 49 11 PM

### PR DESCRIPTION
**Pull request by muhsin-k**
Fixes #2053 
**Preview**
Screenshot 2021-04-06 at 9 17 14 AM

### CODE REVIEW

File: app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue [hunk 1]
```diff
@@ -85,27 +91,25 @@
               {{ $t('PROFILE_SETTINGS.FORM.PASSWORD_CONFIRMATION.ERROR') }}
             </span>
           </label>
+          <woot-submit-button
```
Comment (nithindavid) [inline app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue:94]: Not a blocking suggestion, We have introduced a new button component `woot-button` @ `app/javascript/dashboard/components/ui/WootButton.vue` Can try if it's a good fit here, with the `type="submit"` attribute ?

**Review by nithindavid — DISMISSED** [review]

File: app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue (hunk 1 above)
Comment (muhsin-k) [reply app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue:94]: Sure

**Comment by muhsin-k** [comment]
@nithindavid Please check the latest changes

File: app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue [hunk 2]
```diff
@@ -115,10 +123,12 @@ import { mapGetters } from 'vuex';
 import { clearCookiesOnLogout } from '../../../../store/utils/api';
 import NotificationSettings from './NotificationSettings';
 import alertMixin from 'shared/mixins/alertMixin';
+import WootButton from 'components/ui/WootButton';
```
Comment (nithindavid) [inline app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue:126]: Can you check if this line is needed ?  Since `woot-button` is globally imported in `application.js`.

Comment (muhsin-k) [reply app/javascript/dashboard/routes/dashboard/settings/profile/Index.vue]: @nithindavid Done

**Review by nithindavid — APPROVED** [review]
