### PR TITLE
enhancement: Custom views

### LINKED ISSUE #3826: Custom Views bugs/improvements
### Segments

- [x] Change the name to segments everywhere instead of custom views
- [x] On saving segments in contact, it should redirect to the view and hide the option to save the filter again.
- [x] Pagination button in the contacts doesn't consider filter, it is bringing all the results
- [x] Filter returns unidentified contacts also
- [x] After saving (without refresh) if you click on the segment, it returns the result without applying the filters.
- [x] Loading a custom view fetches the contacts without filters first and then fetches the contacts with filters. See this video https://www.loom.com/share/fb9c4e55969b47d0b5b7a68dd5de2da3

### Folders

- [x] Change the name to folders everywhere instead of custom views
- [x] Change the text "Clear Filters" to "Clear filters"
- [x] Long button text on the delete modal is broken. Keep it simple "Yes, delete" & "No, keep it".
- [ ] Filter breaks when there are multiple pages (Re-opened the custom filter issue handled by Fayaz)
- [x] After saving the folder, it should redirect to the view instead of staying in the filter page.
- [x] Change the toast message from "Custom View deleted successfully" to "Folder deleted successfully"

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #3826 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

ref: #3826 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/components/ChatList.vue [hunk 1]
```diff
@@ -493,6 +495,27 @@ export default {
...
+      });
+    },
+    openLastItemAfterDeleteInFolder() {
+      if (this.folders.length > 0) {
+        const lastItemOfFolder = this.folders[this.folders.length - 1];
+        const lastItemId = lastItemOfFolder.id;
+        this.$router.push({
+          name: 'folder_conversations',
+          params: { id: lastItemId },
+        });
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/ChatList.vue:513]: Can't we direct call `this.openLastSavedItemInFolder()` here?

Comment (pranavrajs) [reply app/javascript/dashboard/components/ChatList.vue:513]: Same for other Segment call as well.

**Review by muhsin-k — APPROVED** [review]
