### PR TITLE
fix: Added "None" option in bulk actions assignment menu

### LINKED ISSUE #5503: add "None" option in bulk actions assignment menu
Add a "None" option to the bulk actions assignment menu.

Screen Shot 2022-09-27 at 9 37 29 AM

Something like the one present already in conversation sidebar assignment menu:

Screen Shot 2022-09-27 at 9 39 23 AM

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Bulk update conversation to `assignee_id: null`

Fixes #5503 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

**Screencast**
https://www.loom.com/share/ff8ec3dd14e147a1951b94e737e7a505

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/jobs/bulk_actions_job.rb [hunk 1]
```diff
@@ -36,7 +36,7 @@ def bulk_remove_labels
   def available_params(params)
     return unless params[:fields]
 
-    params[:fields].delete_if { |_k, v| v.nil? }
+    params[:fields].delete_if { |k, _v| k.nil? }
```
Comment (sojan-official) [inline app/jobs/bulk_actions_job.rb:39]: @tejaswinichile, can the keys here be nil ? Do we need this? 
Also, should we validate the keys in params[:fields]

Comment (tejaswinichile) [reply app/jobs/bulk_actions_job.rb:39]: @sojan-official Yes, this is for bulk action; if keys are present, then only consider updating the values.
The last changes with values nil not helping to update assignee_id to empty/nil.
We are validating these keys in the bulk action controller.

**Review by sojan-official — APPROVED** [review]
