### PR TITLE
Fix: Handled IG unsupported file type

### LINKED ISSUE #5428: ArgumentError: 'unsupported_type' is not a valid file_type
Sentry Issue: [CHATWOOT-T9](https://sentry.io/organizations/chatwoot-p3/issues/3457631234/?referrer=github_integration)

```
ArgumentError: 'unsupported_type' is not a valid file_type
  app/builders/messages/messenger/message_builder.rb:7:in `process_attachment'
    attachment_obj = @message.attachments.new(attachment_params(attachment).except(:remote_file_url))
  app/builders/messages/instagram/message_builder.rb:79:in `block in build_message'
    process_attachment(attachment)
  app/builders/messages/instagram/message_builder.rb:78:in `each'
    attachments.each do |attachment|
  app/builders/messages/instagram/message_builder.rb:78:in `build_message'
    attachments.each do |attachment|
  app/builders/messages/instagram/message_builder.rb:21:in `block in perform'
    build_message
...
(118 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

we get 'unsupported_type' in the web-hook event only when Instagram faces issues processing the attachments. https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook/ according to their document we are handling the given types so we are ignoring this one for now.

Fixes #5428 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested on local with the given type webhook call.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sojan-official — COMMENTED** [review]
LGTM. Can we have a spec for the same?

File: app/builders/messages/messenger/message_builder.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@ class Messages::Messenger::MessageBuilder
   include ::FileTypeHelper
 
   def process_attachment(attachment)
-    return if attachment['type'].to_sym == :template
```
Comment (sojan-official) [inline app/builders/messages/messenger/message_builder.rb:5]: Does this create empty messages? Should we do the filtering at the message creation step itself?

Comment (tejaswinichile) [reply app/builders/messages/messenger/message_builder.rb:5]: Let me check with just attachments and no content.
