### PR TITLE
Bug: Fix wrong error message when existing agent email is reused for a new agent 

### LINKED ISSUE #496: Bug: Wrong error message when existing agent email is reused for a new agent
**Describe the bug**
Wrong error message when existing agent email is reused for a new agent
" cannot connect to server " 

**To Reproduce**
1. Go to agents screen
2. add agent with email 'test@test.com'
3. try to add another agent with same email 'test@test.com'

**Expected behavior**
The error should say agent already exists 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all

### PR DESCRIPTION
**Pull request by ghosteathuman**
Fixes #496

### CODE REVIEW

File: app/javascript/dashboard/api/ApiClient.js [hunk 1]
```diff
@@ -17,7 +17,10 @@ class ApiClient {
   }
 
   create(data) {
-    return axios.post(this.url, data);
+    return axios.post(this.url, data)
```
Comment (pranavrajs) [inline app/javascript/dashboard/api/ApiClient.js]: Why was this changed?

**Comment by pranavrajs** [comment]
@ghosteathuman Thanks for the PR. I've a comment about the API client change.

File: app/javascript/dashboard/api/ApiClient.js (hunk 1 above)
Comment (ghosteathuman) [reply app/javascript/dashboard/api/ApiClient.js]: I was thinking I needed this to bubble the error up.

I was mistaken, it is not required. I will remove this change.
