### PR TITLE
fix: hide linear card when not enabled

### LINKED ISSUE #12909: Linear card is showing even when disabled
### Describe the bug

"Linked Linear Issues" card is showing in conversation sidebar even if Linear feature is not enabled in "/super_admin/accounts/{account_id}/edit".

Image

### To Reproduce

Navigate to "/super_admin/accounts/{account_id}/edit" and disable Linear Integration feature. Then open any conversation to check the presence of "Linked Linear Issues" card in sidebar

### Expected behavior

The Linear block always shows up with CTA when not enabled or with issues list when enabled.

The expected behavior should be:

- Feature disabled in "/super_admin/accounts/{account_id}/edit" → should hide card
- Feature enabled but client id/secret missing → should hide card
- Feature enabled + configured but not connected → show CTA: currently works.
- Feature enabled + configured + connected → show issues list

I can work on this...

### Environment

Heroku

### Cloud Provider

None

### Platform

None

### Operating system

_No response_

### Browser and version

_No response_

### Docker (if applicable)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by digiorgiu**
# Pull Request Template

## Description

The Linear card now only appears in conversation sidebar when:

- The linear_integration feature flag is enabled for the account
- LINEAR_CLIENT_ID is configured (inferred from the integration existing in the store)

This matches the backend behavior: if LINEAR_CLIENT_ID is not set, the integration is filtered out of the API response, so it won't exist in the store.

In addition, I discovered that Settings/Integrations page showed Linear card even if it was disabled but Linear client_id set. Now the Linear card shows only if both conditions are met.

Fixes #12909 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

#### Before

https://github.com/user-attachments/assets/cd21b881-5332-48f8-b230-662abc256ba2

#### After

https://github.com/user-attachments/assets/d794cc2e-19d6-4545-b2ef-3af054c2ac81

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue [hunk 1]
```diff
@@ -40,9 +40,13 @@ const {
   toggleSidebarUIState,
 } = useUISettings();
 
+const store = useStore();
+
 const dragging = ref(false);
 const conversationSidebarItems = ref([]);
 
+const accountId = computed(() => store.getters.getCurrentAccountId);
```
Comment (iamsivin) [inline app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue]:
```suggestion
const accountId = useMapGetter('getCurrentAccountId');
```

File: app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue [hunk 2]
```diff
@@ -52,16 +56,25 @@ const isShopifyFeatureEnabled = computed(
   () => shopifyIntegration.value.enabled
 );
 
+const isLinearFeatureEnabled = useFunctionGetter(
+  'accounts/isFeatureEnabledonAccount',
+  accountId,
+  'linear_integration'
+);
+
```
Comment (iamsivin) [inline app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue:62]: @digiorgiu Let us use `isCloudFeatureEnabled` from `app/javascript/dashboard/composables/useAccount.js`. In that case, we won’t need to import `const accountId = computed(() => store.getters.getCurrentAccountId);`
Also, please use the `FEATURE_FLAGS.LINEAR` constant from `app/javascript/dashboard/featureFlags.js`

File: app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue [hunk 3]
```diff
@@ -40,9 +40,13 @@ const {
   toggleSidebarUIState,
 } = useUISettings();
 
+const store = useStore();
```
Comment (iamsivin) [inline app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue]:
```suggestion
```

**Review by iamsivin — COMMENTED** [review]
@digiorgiu Thanks for the PR, nice work! I’ve added a few minor comments. Could you please take a look?

**Comment by digiorgiu** [comment]
@iamsivin Thanks for the review! I’ve applied the suggested changes.
Let me know if you’d like me to adjust anything further.

**Review by iamsivin — APPROVED** [review]
LGTM
@muhsin-k Could you please take a look and merge the PR?

**Review by muhsin-k — APPROVED** [review]
