### PR TITLE
bug: Fixes Incorrect badge for Twilio SMS inbox and adds the ability to differentiate Twitter tweets and chats

### LINKED ISSUE #2109: Bug: Incorrect avatar icon for twilio sms inbox
Screenshot 2021-04-16 at 4 52 33 PM

The Twilio SMS inbox shows WhatsApp icons on avatars

### LINKED ISSUE #2961: chore: Ability to differentiate between tweets and DMs
## Acceptance 

Ability to differentiate between Twitter tweets and messages in a single glance 

### Dashboard 
Screenshot 2021-09-05 at 11 15 56 PM

### Icon

svg zip : 
[twitter.svg.zip](https://github.com/chatwoot/chatwoot/files/7112076/twitter.svg.zip)

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

## Description

Fixes incorrect badge icon in the thumbnail for Twilio SMS inbox and adds the ability to differentiate between Twitter tweets and chats by adding badge icon.

Fixes #2109 
Fixes #2961 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

File: app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue [hunk 1]
```diff
@@ -11,7 +11,7 @@
     <Thumbnail
       v-if="!hideThumbnail"
       :src="currentContact.thumbnail"
-      :badge="chatMetadata.channel"
+      :badge="thumbnailBadge"
       class="columns"
       :username="currentContact.name"
       :status="currentContact.availability_status"
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue:17]: Please pass a prop 'variant' so that the logic is handled inside the thumbnail component, not here.

Comment (pranavrajs) [reply app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue:17]: Also, please use an icon for SMS inboxes.

**Review by muhsin-k — CHANGES_REQUESTED** [review]
@iamsivin Can we use **inboxMixin** for other inbox badges too?

File: app/javascript/dashboard/components/widgets/Thumbnail.vue [hunk 2]
```diff
@@ -83,6 +92,10 @@ export default {
       type: String,
       default: 'fb',
     },
+    chatInboxId: {
```
Comment (muhsin-k) [inline app/javascript/dashboard/components/widgets/Thumbnail.vue:95]:
```suggestion
    conversationInboxId: {
```

File: app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue [hunk 3]
```diff
@@ -111,6 +112,26 @@ export default {
...
+      if (this.isATwitterInbox) {
+        if (this.chat.additional_attributes.type === 'tweet') {
+          return 'twitter-tweet';
+        }
+        if (this.chat.additional_attributes.type === 'message') {
+          return 'twitter-message';
+        }
+      }
+      return this.chatMetadata.channel;
+    },
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue:133]: This code is repeated below. @iamsivin Can you please move it to mixin or a util?

File: app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue [hunk 4]
```diff
@@ -11,7 +11,7 @@
     <Thumbnail
       v-if="!hideThumbnail"
       :src="currentContact.thumbnail"
-      :badge="chatMetadata.channel"
+      :badge="findInboxBadgeType"
```
Comment (muhsin-k) [inline app/javascript/dashboard/components/widgets/conversation/ConversationCard.vue:14]:
```suggestion
      :badge="inboxBadge"
```

File: app/javascript/shared/mixins/inboxMixin.js [hunk 5]
```diff
@@ -36,12 +36,25 @@ export default {
...
+      const { medium: medium = '' } = this.inbox;
+      return this.isATwilioChannel && medium === 'sms';
     },
     isATwilioWhatsappChannel() {
-      const { phone_number: phoneNumber = '' } = this.inbox;
-      return this.isATwilioChannel && phoneNumber.startsWith('whatsapp');
+      const { medium: medium = '' } = this.inbox;
+      return this.isATwilioChannel && medium === 'whatsapp';
+    },
+    findInboxBadgeType() {
```
Comment (muhsin-k) [inline app/javascript/shared/mixins/inboxMixin.js:46]: Function `findInboxBadgeType` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

File: app/javascript/shared/mixins/inboxMixin.js [hunk 6]
```diff
@@ -36,12 +36,25 @@ export default {
...
+        return `${this.isATwilioSMSChannel ? 'sms' : 'whatsapp'}`;
+      }
+      if (this.isATwitterInbox) {
+        return `${
+          this.chat.additional_attributes.type === 'tweet'
+            ? 'twitter-tweet'
+            : 'twitter-chat'
+        }`;
+      }
+      return this.chat.meta.channel;
```
Comment (pranavrajs) [inline app/javascript/shared/mixins/inboxMixin.js:57]: `this.chat.meta` might not be available in other places, which might make this mixin unusable @muhsin-k Can you please help @iamsivin to fix the issue?

Comment (muhsin-k) [reply app/javascript/shared/mixins/inboxMixin.js:57]: Sure

**Comment by muhsin-k** [comment]
@iamsivin Please add the specs for newly added computed properties in `inboxMixin` ?

**Comment by iamsivin** [comment]
> @iamsivin Please add the specs for newly added computed properties in `inboxMixin` ?

@muhsin-k I have added specs by this commit https://github.com/chatwoot/chatwoot/pull/3003/commits/1a36d290778fa44bb90c6e4232708af6bc85bce6

**Review by muhsin-k — APPROVED** [review]
