### PR TITLE
fix: Fix timestamp auto-update

### LINKED ISSUE #5629: Timestamp Won't Update
Hi there,

We've been running chatwoot for a while now successfully but since the 2.9.1 update we had several issues. One major one is that the chat timestamps won't auto-udpate unless the page is refreshed. They show always "less than a minute ago". See screenshot for reference.

Thanks
Screenshot 2022-10-14 at 9 16 28

### PR DESCRIPTION
**Pull request by KubesDavid**
# Pull Request Template

## Description

Fixes #5629

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by muhsin-k — DISMISSED** [review]
@KubesDavid Thanks for the PR 🔥. The code looks good to me.

File: app/javascript/dashboard/components/ui/TimeAgo.vue [hunk 1]
```diff
@@ -28,51 +26,45 @@ export default {
...
   },
   mounted() {
-    this.timeAgo = this.dynamicTime(this.timestamp);
     if (this.isAutoRefreshEnabled) {
       this.createTimer();
     }
   },
   beforeDestroy() {
-    this.clearTimer();
+    clearInterval(this.timer);
```
Comment (pranavrajs) [inline app/javascript/dashboard/components/ui/TimeAgo.vue:44]: @KubesDavid Can you please rewrite this with `setTimeout` instead of `setInterval`? We had some performance issues previously with missing `clearInterval` calls. It is quite easy to forget and can miss this in the review as well. We would try to use only setTimeout and probably add a linter for the same.

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Usage of setTimeout vs setInterval

**Comment by pranavrajs** [comment]
@iamsivin Once the requested changes are made, can you please test it out?

**Comment by iamsivin** [comment]
@pranavrajs @KubesDavid  I tested it locally and LGTM. 

Found a small issue. Timestamp auto-update is not working for a conversation created within a minute, it will work after a refresh.
https://www.loom.com/share/ed2dce58e49e43038a6812264070b873

**Comment by KubesDavid** [comment]
Good catch, I fixed it.

**Review by iamsivin — APPROVED** [review]
Thanks for the PR 🎉. I tested it locally and LGTM.

**Review by nithindavid — APPROVED** [review]
