### PR TITLE
fix: Macros authorizations

### LINKED ISSUE #5730: Macros - Release v1
Macros CRUD operations and execution is completed already. During the test, we found a couple of improvements/bugs. The list is added below.

#### Permissions:
- [x] Agents can update/delete their own macros.
- [x] Any agent or admin can only delete the macros they created or orphan macros (any macros created by an agent who was previously a part of the team).
- [x] A public macro created by one agent should be available in read-only mode to other agents, it should not be editable. Admins can edit it.
- [x] Admin can change the visibility of all the macros.
- [x] Order macros by ID. (Let us move it to last used later on)

#### UI Update for the permissions

- [ ] If agents/admins are changing a public macro to private, alert them that “You are changing the visibility of the macro. This action would make it private and it would be only available to the agent who created it”. Once confirmed, update the macro.

#### Chores
- [x] Make sure that the macros created_by / edited_by become `null` if an agent is removed from the account.
- [ ] Rename the visibility in the code to public/private instead of global/personal in the code and external facing APIs.

#### New

- [x] #5733
- [x] #5735
- [x] #5736
- [x] #5734

### Bugs

- [x] #5731
- [x] #5732

### PR DESCRIPTION
**Pull request by tejaswinichile**
# Pull Request Template

## Description

Macros policy update.

Fixes #5730 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested on local

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/policies/macro_policy.rb [hunk 1]
```diff
@@ -8,15 +8,17 @@ def create?
...
   end
 
   def update?
-    true
+    author? || @account_user.administrator?
   end
 
   def destroy?
-    true
+    author? || orphan_record?
```
Comment (sojan-official) [inline app/policies/macro_policy.rb:21]: @tejaswinichile  should we let agents delete orphan macros ? I think it makes more sense to give this permission only to admins.

**Review by sojan-official — CHANGES_REQUESTED** [review]
Looks good mostly. Added a comment on destroying permissions. 
Also, can we have the specs for the same?  ( agents not able to delete )

File: app/policies/macro_policy.rb (hunk 1 above)
Comment (tejaswinichile) [reply app/policies/macro_policy.rb:21]: Yes, that does make sense but if the admin is clogged up with the work then we should let the agent delete these records. May be in the future we can come up with the archived state for the orphan records and then let the agent archive it. @pranavrajs Can you confirm?

Comment (pranavrajs) [reply app/policies/macro_policy.rb:21]: Let us not keep the private macros for the admin to delete them. When an agent is deleted, all their private macros are deleted and public macros would get orphaned. Then, all the orphan records can be deleted by an admin. I hope this would solve the burden of an admin to delete everything. Public Macros are anyways helpful for most of the users, so it makes sense to keep them and giving control to an admin to update it.

**Comment by tejaswinichile** [comment]
@sojan-official Please check, I have added the changes according to the discussed policy changes.

**Comment by tejaswinichile** [comment]
Test cases: 

1. Admin can see and update any[public/private] macro. [Change the visibility and data]
2. Admin can delete the public orphan macro
3. Agent/Admin can delete their own macro.
4. Agent can update their own macro.
5. Agent can see all public macros, not other agents' macros.

**Comment by sojan-official** [comment]
@tejaswinichile @pranavrajs  should the admin be able to delete private macros as well, since it's visible to them? 
In that case, we could simplify the destroy policy and don't have to add specific checks for orphan records 

```
def destroy?
    author? || @account_user.administrator?
  end
```

**Comment by tejaswinichile** [comment]
@sojan-official No, only author can delete their macros.
Admin can delete once it is an orphan.

All personal macros are visible to the admin because they can update it further to change the visibility if they think the macro is helpful for other agents.

cc @pranavrajs

**Comment by pranavrajs** [comment]
> should the admin be able to delete private macros as well

The admin can only see the macros that are either their private macros or public macros. For eg: if agent X created a private macro, that would not be visible to the admin.

File: db/schema.rb [hunk 2]
```diff
@@ -577,14 +577,12 @@
...
     t.integer "visibility", default: 0
-    t.bigint "created_by_id", null: false
-    t.bigint "updated_by_id", null: false
+    t.bigint "created_by_id"
+    t.bigint "updated_by_id"
     t.jsonb "actions", default: {}, null: false
     t.datetime "created_at", precision: 6, null: false
     t.datetime "updated_at", precision: 6, null: false
     t.index ["account_id"], name: "index_macros_on_account_id"
-    t.index ["created_by_id"], name: "index_macros_on_created_by_id"
```
Comment (pranavrajs) [inline db/schema.rb:586]: Should we keep this?

Comment (tejaswinichile) [reply db/schema.rb:586]: Yes, we are removing the index as it can be a null value.
