### PR TITLE
Fix: Campaign triggers first_response reporting event

### LINKED ISSUE #4563: Campaign triggers first_response reporting event
Campaigns trigger the first_response reporting event even without agents responding to it. If an outgoing message is created from a campaign, it should not be marked as first-response.

**To reproduce:**

- Create a campaign
- Go to website where web widget is live
- Wait for the campaign message to appear. Click on the campaign.
- See the database/reports to see the first_response time of the conversation.

### PR DESCRIPTION
**Pull request by aswindevps**
## Description

This change prevents the campaign from triggering the first_response reporting event.

Fixes #4563

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

https://www.loom.com/share/99ec5092c7fe4e21a954515b774e42ce

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: app/models/message.rb [hunk 1]
```diff
@@ -6,6 +6,7 @@
 #  content             :text
 #  content_attributes  :json
 #  content_type        :integer          default("text"), not null
+#  created_by          :string
```
Comment (pranavrajs) [inline app/models/message.rb:9]: I think it is better to use content_attributes here.

File: app/models/message.rb [hunk 2]
```diff
@@ -168,7 +169,8 @@ def update_contact_activity
   def dispatch_create_events
     Rails.configuration.dispatcher.dispatch(MESSAGE_CREATED, Time.zone.now, message: self, performed_by: Current.executed_by)
 
-    if outgoing? && conversation.messages.outgoing.count == 1
+    campaign_outgoing_messages = conversation.messages.outgoing.where(created_by: 'Campaign')
```
Comment (pranavrajs) [inline app/models/message.rb:172]: I would suggest saving campaign_id instead of "campaign" text, so it is easy for us to identify the campaign from which the message was triggered.

File: app/models/message.rb [hunk 3]
```diff
@@ -168,7 +169,8 @@ def update_contact_activity
...
+    if outgoing? && (conversation.messages.outgoing.count - campaign_outgoing_messages.count) == 1
```
Comment (pranavrajs) [inline app/models/message.rb:173]: Can't we just query messages where type = outgoing and campaign_id is nil?

File: app/builders/campaigns/campaign_conversation_builder.rb [hunk 4]
```diff
@@ -21,7 +21,8 @@ def perform
 
   def message_params
     ActionController::Parameters.new({
-                                       content: @campaign.message
+                                       content: @campaign.message,
+                                       created_by: 'Campaign'
```
Comment (pranavrajs) [inline app/builders/campaigns/campaign_conversation_builder.rb:25]: I would suggest passing campaign_id here.

**Review by pranavrajs — CHANGES_REQUESTED** [review]
Please see the individual comments.

File: db/migrate/20220503071925_add_created_by_to_message.rb [hunk 5]
```diff
@@ -0,0 +1,5 @@
+class AddCreatedByToMessage < ActiveRecord::Migration[6.1]
+  def change
+    add_column :messages, :created_by, :string, default: nil
```
Comment (sojan-official) [inline db/migrate/20220503071925_add_created_by_to_message.rb:3]: let's use campaign_id as suggested above for the attribute so that it stays consistent with the attribute we have in conversation. We will also be able to add belongs to => campaign association easily then.

Comment (pranavrajs) [reply db/migrate/20220503071925_add_created_by_to_message.rb:3]: Do we need it as a separate attribute or can we add it in the content_attributes? For the large part, this field would be nil, right?

Comment (sojan-official) [reply db/migrate/20220503071925_add_created_by_to_message.rb:3]: We can have it in content_attributes 👍

Comment (aswindevps) [reply db/migrate/20220503071925_add_created_by_to_message.rb:3]: @pranavrajs At the moment the content_attributes column is JSON type. So it's difficult to query campaign_id from content_attributes. We need to take this as tech debt.

Comment (pranavrajs) [reply db/migrate/20220503071925_add_created_by_to_message.rb:3]: @aswindevps I don't think we are querying campaign_id anywhere in this change, right? I guess what @sojan-official meant was that If at all required, we could query it from content_attributes.

Comment (sojan-official) [reply db/migrate/20220503071925_add_created_by_to_message.rb:3]: After this change, we will have to figure out the number of outgoing messages without campaign_id. 
ref: https://github.com/chatwoot/chatwoot/blob/4f9d41962a3f98206297679ff65d72b9ab3af214/app/models/message.rb#L171

File: app/models/message.rb (hunk 1 above)
Comment (aswindevps) [reply app/models/message.rb]: Added new `jsonb` column `additional_attributes`

File: app/models/message.rb (hunk 2 above)
Comment (aswindevps) [reply app/models/message.rb]: Saved `campaign_id`  in `additional_attributes`.

File: app/models/message.rb (hunk 3 above)
Comment (aswindevps) [reply app/models/message.rb]: Updated to : 

outgoing? && conversation.messages.outgoing.where("(additional_attributes->'campaign_id') is null").count == 1

File: app/builders/campaigns/campaign_conversation_builder.rb (hunk 4 above)
Comment (aswindevps) [reply app/builders/campaigns/campaign_conversation_builder.rb]: Done

File: db/migrate/20220503071925_add_created_by_to_message.rb (hunk 5 above)
Comment (aswindevps) [reply db/migrate/20220503071925_add_created_by_to_message.rb]: `if outgoing? && conversation.messages.outgoing.where("(additional_attributes->'campaign_id') is null").count == 1`

**Review by sojan-official — APPROVED** [review]

**Review by tejaswinichile — APPROVED** [review]
LGTM 💯
