### PR TITLE
fix: Throwing error when click load more conversation

### LINKED ISSUE #4048: Throwing `TypeError: Cannot set properties of undefined` in console
**Describe the bug**

When we click to load more conversations in all conversation view throwing `TypeError: Cannot set properties of undefined (setting 'query_operator')` in console

**To Reproduce**

1. Go to All conversation view
2. Click on Load more conversation
3. Open dev tools

**Screencast**

https://user-images.githubusercontent.com/64252451/155256804-a18c4bed-5f14-4938-857c-19b43a28c1e5.mov

### PR DESCRIPTION
**Pull request by iamsivin**
# Pull Request Template

Fixes #4048 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/javascript/dashboard/components/ChatList.vue [hunk 1]
```diff
@@ -219,7 +219,7 @@ export default {
       folders: 'customViews/getCustomViews',
     }),
     hasAppliedFilters() {
-      return this.appliedFilters.length;
+      return this.appliedFilters.length !== 0;
```
Comment (iamsivin) [inline app/javascript/dashboard/components/ChatList.vue:222]: This change, it will fix showing a warning in the console when we apply a filter, which you can see in the below screencast.


https://user-images.githubusercontent.com/64252451/155257777-2d925351-3ce3-4825-a4e3-f7814b258431.mov

**Review by fayazara — APPROVED** [review]
Looks good
