### PR TITLE
fix: un-assign agent from conversation after removal

### LINKED ISSUE #4555: Remove agent from assigned converstion if they are removed from the account
Bug: The agent is still assigned in a conversation even if they are removed from the account.

To reproduce: 

- Add an agent
- Assign a conversation
- Remove them from the conversation

Note: The agent cannot access the conversation as they don't have access to the account, hence it is not a security issue.

### PR DESCRIPTION
**Pull request by shivamsinghchahar**
# Pull Request Template

## Description

Unassign agents from the conversation when they are removed from the account.

Fixes #4555

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested manually

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/models/account_user.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ class AccountUser < ApplicationRecord
   accepts_nested_attributes_for :account
 
   after_create_commit :notify_creation, :create_notification_setting
-  after_destroy :notify_deletion, :remove_user_from_account
+  after_destroy :notify_deletion, :remove_user_from_account, :unassign_conversations
```
Comment (sojan-official) [inline app/models/account_user.rb:36]: let's move this logic to `::Agents::DestroyService` so that all actions that happen on agent delete remain in one place.

**Review by sojan-official — COMMENTED** [review]
😅 review comments I added earlier seemed to be lost. So adding again. 
- let's also add a spec for this case.

**Comment by shivamsinghchahar** [comment]
@sojan-official Made the changes, let me know if anything else is needed.

**Review by sojan-official — APPROVED** [review]
The code looks good to me. We will QA and get this merged.
